### PR TITLE
Force String.toLowerCase() to use Locale.ENGLISH

### LINKED ISSUE #39: No Turkish support, toLowerCase() breaks
`.toLowerCase()` should have a locale forced, if not:

Expected:
`windows_64`

Actual:
`wındows_64` (notice the "i" is incorrect)

### PR DESCRIPTION
**Pull request by tresf**
This is untested, but I believe it will fix the issues described in #39.

Theoretically, closes #39

### CODE REVIEW

**Comment by imagejan** [comment]
I adapted `NativeLoaderTest` to temporarily change to Turkish `Locale`, so that the test fails on Windows without the commit https://github.com/scijava/native-lib-loader/commit/7313c34ffaabb7ddb7bdf511ae33d11cba0e975a by @tresf.

See also the https://github.com/scijava/native-lib-loader/tree/test-issue-39 branch for the failing test on top of `master`.

As the issue seems specific to Windows, the test passes e.g. on Mac OSX no matter if the fix is included or not, but it definitely solves the problem on Windows.

So this PR also practically closes #39 🙂 

Looks good to be merged for me 👍 (/cc @ctrueden)

**Review by Shaquu — APPROVED** [review]
Great addition! Never imagined such a bug.

**Comment by tresf** [comment]
Friendly bump!  What's needed to get this merged?

**Comment by tresf** [comment]
Hi again.  The JSSC project will be releasing a new version very soon, it would be very nice to have this dependency resolved so that we do not have to build a one-off version. https://github.com/java-native/jssc/issues/80 or remove this dependency altogether.

**Comment by hinerm** [comment]
Thanks @imagejan and @tresf! I just cut a `2.3.6` release - let me know if you need anything else :)

**Comment by tresf** [comment]
> Thanks @imagejan and @tresf! I just cut a `2.3.6` release - let me know if you need anything else :)

Thanks!  Any chance you can bump it in Maven as well?

**Comment by imagejan** [comment]
What do you mean by "bump it in Maven"?

@hinerm It seems version `2.3.6` was deployed to [`maven.scijava.org`](https://maven.scijava.org/#nexus-search;gav~org.scijava~native-lib-loader~2.3.6~~) but not to [Maven Central](https://mvnrepository.com/artifact/org.scijava/native-lib-loader), maybe due to the recent migration to GitHub Actions?

**Comment by tresf** [comment]
> version `2.3.6` was deployed to maven.scijava.org but not to Maven Central

Thanks.  The project which originally exposed this bug uses the maven central mirror.

**Comment by ctrueden** [comment]
Weird... according to the POM configuration, the 2.3.6 release should have gone to OSS Sonatype and therefore be available from Maven Central. I'll see if I can figure out why this failed to deploy as desired.

**Comment by ctrueden** [comment]
I figured out what went wrong, and fixed some problems:

1. The `ci-build.sh` script case for doing releases never triggered, even on release tags, due to a bug. I fixed it now.
2. We were pinned to `maven-gpg-plugin` version 1.6, but it's not compatible with gpg 2.1+. I added a hack to the `ci-build.sh` script to force `maven-gpg-plugin.version` to 3.0.1 if it's less than 3.0.1, and updated pom-scijava-base to use 3.0.1 from (not-yet-released) version 31.0.0 onward. This fixed some GPG signing errors.

Unfortunately, I still don't have GPG signing of releases working on GitHub Actions. We can't deploy to OSS Sonatype again until that is fixed. I'll keep working on it, and get native-lib-loader 2.3.6 onto Central as soon as I can.

**Comment by tresf** [comment]
> I'll get native-lib-loader 2.3.6 onto Central as soon as I can.

Hi, friendly bump. Maven Central is still showing 2.3.5: https://mvnrepository.com/artifact/org.scijava/native-lib-loader.  🍻

**Comment by ctrueden** [comment]
@tresf I finally got native-lib-loader 2.3.6 deployed to Maven Central, where it should be. Sorry for the delay on that. We just completed a migration from Travis CI to GitHub Actions, and there were some kinks to iron out.

**Pull request merged**
