### PR TITLE
Add more documentation to README, add tests and little boyscouting

### PR DESCRIPTION
**Pull request by nitram509**
Hi,

I've added some more text to the README to kickstart using this project.
Additionally I've did some boyscouting to gain quick-fixes like fix java docs, 
remove empty finally-block, extract method, reader.close(), etc.
I avoided changing API or behavior, but added also simple unit tests.

Feedback is welcome.

Regards
Martin

### CODE REVIEW

**Comment by ctrueden** [comment]
I love everything about this, except for the switch from JUnit to TestNG (every other SciJava project uses JUnit). Given that there weren't any existing unit tests here, I'm going to merge as-is. But I will make a quick attempt to switch back to JUnit, since the new test looks really simple.

**Comment by ctrueden** [comment]
Ooh, one other problem. I forgot that this component was still targeting Java 1.5. You changed `indexOf(...) >= 0` to `contains(...)` which is Java 6+ only. But I am comfortable upping the source requirement to Java 6 now, so no big deal.

**Comment by ctrueden** [comment]
Hmm, I guess I am wrong, and `contains` is valid for `String` in Java 1.5. OK, never mind then. :smile:

**Comment by ctrueden** [comment]
I made the switch to JUnit: 6dabcd249b1dec7e9ba024b46ddb2e28fc4d55f0.

**Comment by nitram509** [comment]
Thank you very much for this feedback.

**Pull request merged**
