### PR TITLE
Switch logging to SLF4J

### PR DESCRIPTION
**Pull request by ctrueden**
See #11.

### CODE REVIEW

**Comment by ctrueden** [comment]
/cc @sbesson 
Please feel free to merge if you like this.

**Comment by ctrueden** [comment]
See also scijava/pom-scijava@e838394ae0063d6a62fa451782d8106e81661e9f

**Comment by sbesson** [comment]
Thanks @ctrueden. I will have a go at this PR once the pending [Bio-Formats logging improvements](https://github.com/openmicroscopy/bioformats/pull/2372) are reviewed.

**Comment by sbesson** [comment]
Tested primarily using the Bio-Formats command-line tools with the SlideBook6 reader which consumes this library. Everything works as expected with different log levels configured via `logback`. I have a separate proposal for reducing the logging level of the exceptions catched in `NativeLibraryUtil` but I am happy to open it as a follow-up PR for discussion.

**Comment by ctrueden** [comment]
OK, so I am assuming you want this, then. Thanks.

**Pull request merged**
